name: floor2drift_annotation
description: This library contains the annotations used by the floor2Drift library
version: 1.0.0
repository: https://github.com/ViveNoctem/Floor2Drift
issue_tracker: https://github.com/ViveNoctem/Floor2Drift/issues
resolution: workspace

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
