name: floor2drift
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:

  flutter:
    sdk: flutter

  # path: ^1.8.0
  build: ^2.4.0
  source_gen: ^1.4.0
  analyzer: '>=5.13.0 <7.0.0'
  floor_annotation: ^1.5.0
  floor2drift_annotation:
    path: ./../floor2drift_annotation
  sqlparser: ^0.34.1
  json_annotation: ^4.9.0
  args: ^2.7.0
  logging: ^1.3.0
  glob: ^2.1.3
  code_builder: ^4.11.0
  dart_style: ^2.3.8
  path: ^1.9.1
  meta: ^1.16.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: 5.4.4
  floor: ^1.5.0
  floor_generator: ^1.5.0
  drift: ^2.16.0
  build_runner: ^2.4.8
  drift_dev: ^2.16.0
